### ISSUE TITLE
ISO8583 Connector TestServer can not receive  the message unless i restart the ESB!

### ISSUE THREAD

**Issue by Adnan-Alnayb** [wso2-extensions/esb-connector-iso8583#6]
Hello @Kanapriya

I have implemented all the mentioned instruction in the official wso2 inbound and connector [documentation](https://docs.wso2.com/display/ESBCONNECTORS/ISO8583+Connector+and+Inbound), when i send the message to the JavaTest server the proxy service that i used to send  XML Message through stop working and nothing appear in the log, Alos the server does not receive the ISO message unless i restart the ESB, the message shown up in the server once I restart it! 

Thank you,

**Comment by anupama-pathirage** [comment]
Moved the issue to https://github.com/wso2/micro-integrator/issues/3497
